server:
  port: 80
  context-path:
  session:
    cookie:
      path: /

spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://188.131.172.54:3306/kfcg?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
#    password: 123456
    password: xdjr1230-KFCG
#    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      suffix: .ftl
      prefix: /templates/
  freemarker:
          #cache: false
          request-context-attribute: request
          settings:
            template_exception_handler: ignore
  redis:
    host: 188.131.172.54
    port: 6379
mybatis:
  #实体类所做包
  type-aliases-package: com.kf.pojo
  #mappers.xml所在位置
  mapper-locations: classpath:mappers/*.xml
  #开启redis 二级缓存
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true

# LOGGING
logging:
    level:
       com.kf.mapper: debug
       com.kf.controller: debug
       com.kf.Interceptor: debug


page:
  pageSize: 10

path:
  pathValue: /home/kfcg/
pagehelper:
  helper-dialect: mysql
